stages:
  - test
  - build
  - package
  - deploy


unit-tests:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:5.0-buster-slim
  only:
    - merge_requests
    - branches
  script:
    - 'dotnet test --test-adapter-path:. --logger:"junit;LogFilePath=..\artifacts\{assembly}-test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose"'
  tags:
    - linux
    - docker
  artifacts:
    when: always
    paths:
      - ./**/*test-result.xml
    reports:
      junit:
        - ./**/*test-result.xml

build-release:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:5.0-buster-slim
  tags:
    - linux
    - docker
  script:
    - dotnet publish -o package/Publish
  artifacts:
    paths:
      - ./package/Publish

# build-debian-package:
#   stage: package