stages:
  - test
  - build
  - package
  - deploy


unit-tests:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:5.0-buster-slim
  only:
    - merge_requests
    - branches
  script:
    - 'dotnet test --test-adapter-path:. --logger:"junit;LogFilePath=..\artifacts\{assembly}-test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose"'
  tags:
    - linux
    - docker
  artifacts:
    when: always
    paths:
      - ./**/*test-result.xml
    reports:
      junit:
        - ./**/*test-result.xml

build-release:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:5.0-buster-slim
  tags:
    - linux
    - docker
  before_script:
    - curl -sL https://deb.nodesource.com/setup_14.x | bash -
    - apt-get install -y nodejs
  script:
    - dotnet publish -o Publish
  needs:
    - job: unit-tests
      artifacts: false
  artifacts:
    paths:
      - ./Publish

build-debian-package:
  stage: package
  image: debian:buster
  tags:
    - linux
    - docker
  before_script:
    - apt-get install -y tree
  script:
    - tree ./package
    - mkdir -p package/debian/sentinel/usr/share/Sentinel
    - tree ./package
    - cp -rv Publish/* package/debian/sentinel/usr/share/Sentinel/
    - tree ./package
    - cd ./package/debian
    - tree
    - dpkg-deb --build sentinel
  needs:
    - job: build-release
      artifacts: true
  artifacts:
    paths:
      - ./package/debain/*.deb