stages:
  - test
  - build
  - package
  - deploy


unit-tests:
  stage: test
  image: registry.corp.soullessgingers.net/dotnet-sdk:5.0-buster-slim
  only:
    - merge_requests
    - branches
  before_script:
    - 'dotnet restore --packages .nuget'
  script:
    - 'dotnet test --no-restore --test-adapter-path:. --logger:"junit;LogFilePath=..\artifacts\{assembly}-test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose"'
  tags:
    - linux
    - docker
  cache:
    key: '$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG'
    paths:
      - '*/obj/project.assets.json'
      - '*/obj/*.csproj.nuget.*'
      - '.nuget'
  artifacts:
    when: always
    paths:
      - ./**/*test-result.xml
    reports:
      junit:
        - ./**/*test-result.xml

build-release:
  stage: build
  image: registry.corp.soullessgingers.net/dotnet-sdk:5.0-buster-slim
  tags:
    - linux
    - docker
  before_script:
    - 'dotnet restore --packages .nuget'
  script:
    - scripts/dotnet_build.sh
  needs:
    - job: unit-tests
      artifacts: false
  cache:
    key: '$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG'
    paths:
      - 'Sentinel.Web/ClientApp/node_modules/*'
      - '*/obj/project.assets.json'
      - '*/obj/*.csproj.nuget.*'
      - '.nuget'
  artifacts:
    paths:
      - ./Publish

build-debian-package:
  stage: package
  image: debian:buster
  tags:
    - linux
    - docker
  script:
    - package/scripts/build_debian_package.sh
  needs:
    - job: build-release
      artifacts: true
  artifacts:
    paths:
      - ./package/debian/*.deb

deploy-debian-package:
  stage: deploy
  image: debian:buster
  only:
    - master
    - develop
    - /^release/.*$/
  tags:
    - linux
    - docker
  before_script:
    - apt-get update
    - apt-get install -y openssh-client
  script:
    - package/scripts/deploy_debian_package.sh
  needs:
    - job: build-debian-package
      artifacts: true
